    version: '2'
    services:

      comex_db:
        image: comex2_mysql_server:latest
        build: ./comex2_mysql_server
        container_name: comex_db
        environment:
         - MYSQL_ROOT_PASSWORD=very-safe-pass
        volumes:
         - ../../data/shared_mysql_data:/var/lib/mysql

      comex_test:
        container_name: comex_test
        image: comex2_services:testing
        build: ./comex2_services
        # logs will show all that's printed to STDOUT with tty:true
        tty: true
        ports:
         # we expose the entire contained nginx
         - "8080:80"
        links:
         - comex_db
        volumes:
         # /!\ this uses outside conf to replace :contained conf
         - ../../config:/comex2/config
         # similar logic used to expose inner logs
         - ../../logs:/comex2/logs
         # and user images
         - ../../data/shared_user_img:/comex2/data/shared_user_img
         # and to pass the ssl keys
         - /etc/ssl/certs/:/etc/ssl/certs/
         - /etc/ssl/private/:/etc/ssl/private/
        environment:
            # override values from parametres_comex.ini
            # for a double reason:
            #   - both apps have ENV vals preempt INI vals
            #   - if we're here (in docker-compose) then by definition the mysql must be coming from comex_db container
            - SQL_HOST=comex_db
            - SQL_PORT=3306
